# Generated by Django 3.1.2 on 2020-10-21 17:23

from django.db import migrations, models
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_productos_img_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='img_product',
        ),
        migrations.AddField(
            model_name='productos',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=ventas.models.upload_to, verbose_name='Avatar'),
        ),
    ]
