# Generated by Django 3.1.2 on 2020-10-21 18:12

from django.db import migrations, models
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20201021_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='avatar',
        ),
        migrations.AddField(
            model_name='productos',
            name='img_product',
            field=models.ImageField(blank=True, upload_to=ventas.models.upload_to, verbose_name='Img_product'),
        ),
    ]
